#!/bin/bash
# Rebuilds tg2sip-webrtc's C++ dependencies (TDLib, PJSIP, spdlog, abseil)
# under Clang+libc++ instead of the system default GCC+libstdc++, installing
# them all into a single prefix that CMakePresets.json's "clang-libcxx"
# preset then picks up via CMAKE_PREFIX_PATH.
#
# Why: pytgcalls/ntgcalls (the replacement for the dead tgcalls dependency -
# see the ntgcalls migration plan/memory) ships a prebuilt WebRTC static
# library that is unconditionally compiled with Clang+libc++. Mixing that
# with a GCC+libstdc++ build of everything else is a binary ABI mismatch at
# link time, not something a CMake flag can paper over - the whole C++
# toolchain has to match. Plain C libraries (opus, ffmpeg, X11, openssl,
# ...) are unaffected and need no changes.
#
# Usage: PREFIX=~/somewhere TD_SRC=~/td PJPROJECT_SRC=~/pjproject ./build-clang-libcxx-deps.sh
# All paths below default to the layout used during the original migration.

set -e

PREFIX="${PREFIX:-$HOME/claudetmp/toolchain-libcxx-install}"
TD_SRC="${TD_SRC:-$HOME/claudetmp/td}"
PJPROJECT_SRC="${PJPROJECT_SRC:-$HOME/claudetmp/pjproject-clang}"
SPDLOG_VERSION="${SPDLOG_VERSION:-v1.15.2}"   # matches Debian's libspdlog-dev
ABSEIL_TAG="${ABSEIL_TAG:-20240722.0}"        # matches Debian's libabsl-dev

mkdir -p "$PREFIX"
JOBS="$(nproc)"

echo "=== Installing clang + libc++ if not already present ==="
if ! command -v clang++ >/dev/null; then
    sudo apt-get install -y clang libc++-dev libc++abi-dev
fi

echo "=== TDLib ==="
# TDLib's checked-in generated sources (td/generate/auto, tdutils/generate/auto)
# get written to during the build. If a previous build ran as root (e.g. via
# sudo make install from an old Docker-based flow), those files end up
# root-owned and a later non-root build fails with EACCES trying to
# regenerate them (crashes as "Assertion error! SIGABRT", not an obvious
# permission message) - fix ownership first.
sudo chown -R "$(id -u):$(id -g)" "$TD_SRC/td/generate/auto" "$TD_SRC/tdutils/generate/auto" 2>/dev/null || true
cmake -S "$TD_SRC" -B "$TD_SRC/build-clang" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
    -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++" \
    -DCMAKE_SHARED_LINKER_FLAGS="-stdlib=libc++"
cmake --build "$TD_SRC/build-clang" -j"$JOBS"
cmake --install "$TD_SRC/build-clang"

echo "=== PJSIP (built in-tree via autoconf, not out-of-source) ==="
# Assumes $PJPROJECT_SRC is a pjproject checkout with buildenv/config_site.h
# already copied to pjlib/include/pj/config_site.h (see buildenv/config_site.h
# in this repo).
(
    cd "$PJPROJECT_SRC"
    make distclean >/dev/null 2>&1 || true
    CC=clang CXX=clang++ \
        CFLAGS="-O3 -DNDEBUG -fPIC" \
        CXXFLAGS="-O3 -DNDEBUG -fPIC -stdlib=libc++" \
        LDFLAGS="-stdlib=libc++" \
        ./aconfigure --disable-sound --prefix="$PREFIX"
    make dep
    make -j"$JOBS"
    sudo make install
)
# The autogenerated libpjproject.pc hardcodes "-lstdc++" in its C++ link
# libs (a template default, independent of which compiler actually built
# it) - that reintroduces exactly the ABI mixing this whole script exists to
# avoid. Strip it; -stdlib=libc++ at link time already pulls in the right
# runtime.
sed -i 's/-lstdc++ //' "$PREFIX/lib/pkgconfig/libpjproject.pc"

echo "=== spdlog (Debian ships a GCC-built libspdlog1.15; need a libc++ one) ==="
SPDLOG_SRC="${SPDLOG_SRC:-$HOME/claudetmp/spdlog}"
if [ ! -d "$SPDLOG_SRC" ]; then
    git clone --branch "$SPDLOG_VERSION" --depth 1 https://github.com/gabime/spdlog.git "$SPDLOG_SRC"
fi
cmake -S "$SPDLOG_SRC" -B "$SPDLOG_SRC/build" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
    -DCMAKE_SHARED_LINKER_FLAGS="-stdlib=libc++" \
    -DSPDLOG_BUILD_SHARED=ON
cmake --build "$SPDLOG_SRC/build" -j"$JOBS"
cmake --install "$SPDLOG_SRC/build"

echo "=== abseil-cpp (Debian ships a GCC-built libabsl-dev; tg_owt/tgcalls needs a libc++ one) ==="
ABSEIL_SRC="${ABSEIL_SRC:-$HOME/claudetmp/abseil-cpp}"
if [ ! -d "$ABSEIL_SRC" ]; then
    git clone --branch "$ABSEIL_TAG" --depth 1 https://github.com/abseil/abseil-cpp.git "$ABSEIL_SRC"
fi
cmake -S "$ABSEIL_SRC" -B "$ABSEIL_SRC/build" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
    -DCMAKE_SHARED_LINKER_FLAGS="-stdlib=libc++" \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DABSL_PROPAGATE_CXX_STD=ON \
    -DCMAKE_CXX_STANDARD=17
cmake --build "$ABSEIL_SRC/build" -j"$JOBS"
cmake --install "$ABSEIL_SRC/build"

echo "=== Done. Build tg2sip-webrtc itself with: cmake --preset clang-libcxx && cmake --build build-clang ==="
echo "=== Note: shared libs land in $PREFIX/lib - the build tree's binary picks them up via CMake's automatic build-RPATH; if you move the binary elsewhere, set LD_LIBRARY_PATH=$PREFIX/lib ==="
